"use client"

import { useState } from 'react'
import Link from 'next/link'
import { SiteChrome } from '@/components/site-header'

export default function ContactPage() {
  const [sent, setSent] = useState(false)
  return <SiteChrome><main className="min-h-screen bg-background pt-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-24"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-accent">Get in touch</p><h1 className="mt-5 font-serif text-5xl leading-[1.02] tracking-tight sm:text-7xl">Let&apos;s talk about the good stuff.</h1><p className="mt-7 max-w-md leading-7 text-muted-foreground">Have a product question, a partnership idea, or a thoughtful recommendation? We&apos;d love to hear from you.</p><div className="mt-10 flex flex-col gap-4 text-sm"><a href="mailto:hello@commonly.example" className="font-medium underline underline-offset-4">hello@commonly.example</a><span className="text-muted-foreground">Monday—Friday, 9am—5pm UTC</span></div></div><div className="border border-border bg-card p-6 sm:p-10"><h2 className="font-serif text-3xl">Send a note</h2>{sent ? <div className="mt-10 border-l-2 border-accent pl-5"><p className="font-medium">Thanks for reaching out.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Your note is ready to be answered. We&apos;ll be in touch soon.</p><Link href="/" className="mt-6 inline-block text-sm underline underline-offset-4">Return home</Link></div> : <form className="mt-8 flex flex-col gap-5" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label className="flex flex-col gap-2 text-sm font-medium">Name<input required className="h-11 border border-input bg-background px-3 font-normal outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label className="flex flex-col gap-2 text-sm font-medium">Email<input required type="email" className="h-11 border border-input bg-background px-3 font-normal outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label className="flex flex-col gap-2 text-sm font-medium">Message<textarea required rows={5} className="resize-none border border-input bg-background p-3 font-normal outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><button className="h-11 bg-primary px-5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90">Send message</button></form>}</div></div></main></SiteChrome>
}
